# conda環境構築

In [ ]:
#参考：https://towardsdatascience.com/conda-google-colab-75f7c867a522

In [1]:
!echo $PYTHONPATH
#PYTHONPATHが設定されているとANACONDAでエラーが出る
%env PYTHONPATH=
!echo $PYTHONPATH

/env/python
env: PYTHONPATH=



In [2]:
#COLABデフォルトの3.6系に合わせたminicondaのインストール
%%bash
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.4-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

PREFIX=/usr/local
installing: python-3.6.5-hc3d631a_2 ...
installing: ca-certificates-2018.03.07-0 ...
installing: conda-env-2.6.0-h36134e3_1 ...
installing: libgcc-ng-7.2.0-hdf63c60_3 ...
installing: libstdcxx-ng-7.2.0-hdf63c60_3 ...
installing: libffi-3.2.1-hd88cf55_4 ...
installing: ncurses-6.1-hf484d3e_0 ...
installing: openssl-1.0.2o-h20670df_0 ...
installing: tk-8.6.7-hc745277_3 ...
installing: xz-5.2.4-h14c3975_4 ...
installing: yaml-0.1.7-had09818_2 ...
installing: zlib-1.2.11-ha838bed_2 ...
installing: libedit-3.1.20170329-h6b74fdf_2 ...
installing: readline-7.0-ha6073c6_4 ...
installing: sqlite-3.23.1-he433501_0 ...
installing: asn1crypto-0.24.0-py36_0 ...
installing: certifi-2018.4.16-py36_0 ...
installing: chardet-3.0.4-py36h0f667ec_1 ...
installing: idna-2.6-py36h82fb2a8_1 ...
installing: pycosat-0.6.3-py36h0a5515d_0 ...
installing: pycparser-2.18-py36hf9f622e_1 ...
installing: pysocks-1.6.8-py36_0 ...
installing: ruamel_yaml-0.15.37-py36h14c3975_2 ...
installing: six-1.11

--2020-12-21 16:18:55--  https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c94f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh [following]
--2020-12-21 16:18:55--  https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8203, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58468498 (56M) [application/x-sh]
Saving to: ‘Miniconda3-4.5.4-Linux-x86_64.sh’

     0K .......... .......... .......... .......... ..........  0% 4.63M 12s
    50K .......... .......... .......... .......... ..........  0

In [3]:
!which conda
!conda --version
!which python
!python --version

/usr/local/bin/conda
conda 4.5.4
/usr/local/bin/python
Python 3.6.5 :: Anaconda, Inc.


In [4]:
#3.6系のままcondaをアップデート
%%bash
conda install --channel defaults conda python=3.6 --yes
conda update --channel defaults --all --yes

Solving environment: ...working... done

## Package Plan ##

  environment location: /usr/local

  added / updated specs: 
    - conda
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-20.3.3                 |   py36h06a4308_0         2.0 MB
    wheel-0.36.2               |     pyhd3eb1b0_0          31 KB
    certifi-2020.12.5          |   py36h06a4308_0         144 KB
    xz-5.2.5                   |       h7b6447c_0         438 KB
    brotlipy-0.7.0             |py36h27cfd23_1003         349 KB
    yaml-0.2.5                 |       h7b6447c_0          87 KB
    _libgcc_mutex-0.1          |             main           3 KB
    libedit-3.1.20191231       |       h14c3975_1         121 KB
    six-1.15.0                 |   py36h06a4308_0          27 KB
    tqdm-4.54.1                |     pyhd3eb1b0_0          54 KB
    ruamel_yaml-0.15.87        |   py36h7b6447c_1   

pip-20.3.3           |  2.0 MB | ########## | 100% 
wheel-0.36.2         |   31 KB | ########## | 100% 
certifi-2020.12.5    |  144 KB | ########## | 100% 
xz-5.2.5             |  438 KB | ########## | 100% 
brotlipy-0.7.0       |  349 KB | ########## | 100% 
yaml-0.2.5           |   87 KB | ########## | 100% 
_libgcc_mutex-0.1    |    3 KB | ########## | 100% 
libedit-3.1.20191231 |  121 KB | ########## | 100% 
six-1.15.0           |   27 KB | ########## | 100% 
tqdm-4.54.1          |   54 KB | ########## | 100% 
ruamel_yaml-0.15.87  |  256 KB | ########## | 100% 
pyopenssl-20.0.1     |   48 KB | ########## | 100% 
libffi-3.3           |   54 KB | ########## | 100% 
chardet-4.0.0        |  213 KB | ########## | 100% 
idna-2.10            |   56 KB | ########## | 100% 
cffi-1.14.4          |  224 KB | ########## | 100% 
cryptography-3.3.1   |  638 KB | ########## | 100% 
urllib3-1.26.2       |   99 KB | ########## | 100% 
conda-package-handli |  967 KB | ########## | 100% 
sqlite-3.33.

In [5]:
!conda --version
!python --version

conda 4.9.2
Python 3.6.12 :: Anaconda, Inc.


In [6]:
#condaで入れたパッケージのパスを追加
import sys
sys.path
sys.path.append("/usr/local/lib/python3.6/site-packages")

In [7]:
!conda install -y -c rdkit rdkit

Solving environment: / - \ | / - \ | / done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - rdkit


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-1.0                   |              mkl           6 KB
    bzip2-1.0.8                |       h7b6447c_0          78 KB
    cairo-1.14.12              |       h8948797_3         906 KB
    fontconfig-2.13.0          |       h9420a91_0         227 KB
    freetype-2.10.4            |       h5ab3b9f_0         596 KB
    glib-2.66.1                |       h92f7085_0         2.9 MB
    icu-58.2                   |       he6710b0_3        10.5 MB
    intel-openmp-2020.2        |              254         786 KB
    jpeg-9b                    |       h024ee3a_2         214 KB
    lcms2-2.11                 |       h396b838_0         307 KB
    libboost-1.73.0            |      h37e3b65_1

In [ ]:
# !conda install -c conda-forge rdkit --yes

# 主題

In [8]:
import pandas as pd
import numpy as np
import rdkit
from rdkit import Chem
from rdkit.Chem import AllChem, Draw, Descriptors, DataStructs
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem import PandasTools as pdt

In [9]:
df = pd.read_csv("https://raw.githubusercontent.com/jiai-edu/teaching_ep_elementary-phython/master/datasets/Grisoni_et_al_2016_EnvInt88.csv")
df

CAS                                   SMILES  ... Class  logBCF
0      100-02-7                  O=[N+](c1ccc(cc1)O)[O-]  ...     1    0.74
1      100-17-4                 O=[N+](c1ccc(cc1)OC)[O-]  ...     1    0.93
2      100-18-5                     c1cc(ccc1C(C)C)C(C)C  ...     3    3.24
3      100-25-4       O=[N+]([O-])c1ccc(cc1)[N+](=O)[O-]  ...     3   -0.40
4      100-40-3                             C=CC1CCC=CC1  ...     1    2.24
..          ...                                      ...  ...   ...     ...
774     99-30-9          O=[N+]([O-])c1cc(c(N)c(c1)Cl)Cl  ...     1    1.88
775  99387-89-0  FC(F)(F)c2cc(ccc2(N=C(n1cncc1)COCCC))Cl  ...     2    2.59
776     99-65-0       O=[N+]([O-])c1cccc(c1)[N+](=O)[O-]  ...     1    0.77
777     99-71-8                        CC(c1ccc(cc1)O)CC  ...     3    1.35
778     99-99-0                  O=[N+](c1ccc(cc1)C)[O-]  ...     1    0.91

[779 rows x 14 columns]

In [17]:
df.columns

Index(['CAS', 'SMILES', 'Set', 'nHM', 'piPC09', 'PCD', 'X2Av', 'MLOGP', 'ON1V',
       'N-072', 'B02[C-N]', 'F04[C-O]', 'Class', 'logBCF'],
      dtype='object')

In [27]:
df_list = df['SMILES'].values.tolist()
df_list

['O=[N+](c1ccc(cc1)O)[O-]',
 'O=[N+](c1ccc(cc1)OC)[O-]',
 'c1cc(ccc1C(C)C)C(C)C',
 'O=[N+]([O-])c1ccc(cc1)[N+](=O)[O-]',
 'C=CC1CCC=CC1',
 'C=Cc1ccccc1',
 'CNc1ccccc1',
 'O=P(OC)(OC)Oc1ccccc1',
 'Clc1c(ccc(c1)Cc1cc(c(cc1)N)Cl)N',
 'O=C(Nc1ccc(c(c1)Cl)Cl)Nc1ccc(cc1)Cl',
 'O=C(OC(C)C)Nc1cccc(c1)Cl',
 'n1c(nc(nc1NCC)SC)NCC',
 'Oc1ccc(cc1)Cc1ccccc1',
 'Nc1ccc(cc1)Cc1ccc(cc1)N',
 'C(c1ccccc1)c1ccccc1',
 'O(c1ccccc1)c1ccccc1',
 'N=C(Nc1ccccc1)Nc1ccccc1',
 'C=CCN(CC=C)CC=C',
 'OCCN(CCO)CCO',
 'O1CCN(CC1)CC(C)C',
 'CCC(CCCC)COC=C',
 'C(c1ccccc1)OCc1ccccc1',
 'CCNc1ccccc1',
 'CN(Cc1ccccc1)C',
 'Clc1c(c(cc(c1)Cl)Cl)Oc1ccc(cc1Cl)Cl',
 'Oc1ccc(cc1)CCCCCCCCC',
 'CC(=CC1C(C1(C)C)C(=O)OCc1coc(c1)Cc1ccccc1)C',
 'O=Cc1ccc(cc1)Cl',
 'CCc1ccc(cc1)CC',
 'C=Cc1ccc(C=C)cc1',
 'CNc1ccc(cc1)C(=O)O',
 'O=C(OCC#C)C(Oc2ccc(Oc1ncc(cc1(F))Cl)cc2)C',
 'Oc1ccc(cc1C)C',
 'O=C(NC1=Nc2c(cccc2)N1)OC',
 'Brc1ccc(cc1)Br',
 'Oc1ccc(cc1)Br',
 'c1cc(ccc1C)C',
 'Cc1ccc(cc1)Cl',
 'c1cc(ccc1Cl)Cl',
 'Nc1ccc(cc1)Cl',
 'Oc1ccc(cc

In [31]:
df_ms = [Chem.MolFromSmiles(df_list[i]) for i in range(len(df_list))]
df_ms

In [43]:
from rdkit import DataStructs
from rdkit.Chem.Fingerprints import FingerprintMols
ms = [Chem.MolFromSmiles('CCOC'), Chem.MolFromSmiles('CCO'), Chem.MolFromSmiles('COC')]
'''print(ms[0])
print(ms[1])
print(ms[2])
'''

fps = [FingerprintMols.FingerprintMol(x) for x in ms]
'''DataStructs.FingerprintSimilarity(fps[0],fps[1])
DataStructs.FingerprintSimilarity(fps[0],fps[2])
DataStructs.FingerprintSimilarity(fps[1],fps[2])
'''

for i in range(3):
  print(fps[i])

In [44]:
#print(df_list[0])
#print(df_ms[0])

fps = [FingerprintMols.FingerprintMol(df_ms[i]) for i in range(len(df_ms))]
print(fps)

[<rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e3c710>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e24440>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e249e0>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e243f0>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2fc60>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2fe90>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2ff30>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2f760>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2f530>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2f800>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2f9e0>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2f850>, <rdkit.DataStructs.cDataStructs.ExplicitBitVect object at 0x7fc522e2f990>, <rdkit.DataStructs.cData

In [46]:
TopologicalFingerprints = [FingerprintMols.FingerprintMol(df_ms[i]) for i in range(len(df_ms))]

In [47]:
from rdkit.Chem import MACCSkeys
MACCS_Keys = [MACCSkeys.GenMACCSKeys(df_ms[i]) for i in range(len(df_ms))]

In [48]:
from rdkit.Chem.AtomPairs import Pairs
AtomPairs_and_TopologicalTorsions = [Pairs.GetAtomPairFingerprint(df_ms[i]) for i in range(len(df_ms))]

In [49]:
from rdkit.Chem.AtomPairs import Torsions
TopologicalTorsion = [Torsions.GetTopologicalTorsionFingerprintAsIntVect(df_ms[i]) for i in range(len(df_ms))]

In [50]:
MorganFingerprint = [AllChem.GetMorganFingerprint(df_ms[i],2) for i in range(len(df_ms))]

In [84]:
MorganFingerprint2 = [AllChem.GetMorganFingerprintAsBitVect(df_ms[i],2,2048) for i in range(len(df_ms))]
MorganFingerprint2

In [71]:
type(MorganFingerprint[0])

rdkit.DataStructs.cDataStructs.UIntSparseIntVect

In [89]:
print(MorganFingerprint[0])
print(MorganFingerprint2[0])

In [90]:
for i in range(len(MorganFingerprint)):
  print(MorganFingerprint[i])

In [56]:
TF_df = pd.Series(TopologicalFingerprints)
type(TF_df)

pandas.core.series.Series

In [57]:
TF_df = pd.Series(TopologicalFingerprints)
MAC_df = pd.Series(MACCS_Keys)
APTT_df = pd.Series(AtomPairs_and_TopologicalTorsions)
TT_df = pd.Series(TopologicalTorsion)
MF_df = pd.Series(MorganFingerprint)

In [58]:
print(type(TF_df), type(MAC_df), type(APTT_df), type(TT_df), type(MF_df))

<class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'>


In [69]:
df_all = pd.DataFrame({"TopologicalFingerprints":TF_df,
                       "MACCS_Keys":MACCS_Keys,
                       "AtomPairs_and_TopologicalTorsions":APTT_df,
                       "TopologicalTorsion":TT_df,
                       "MorganFingerprint":MF_df})
df_all

TopologicalFingerprints  ...                                  MorganFingerprint
0    [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
1    [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
2    [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
3    [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
4    [0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
..                                                 ...  ...                                                ...
774  [0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
775  [1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
776  [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
777  [1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...
778  [0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, ...  ...  <rdkit.DataStructs.cDataStructs.UIntSparseIntV...

[779 rows x 5 columns]

In [83]:
df_all.to_csv("/content/FingerPrints_Grisoni_et_al_2016_EnvInt88.csv")

In [ ]:
df["Fsp3"] = df["ROMol"].map(Descriptors.FractionCSP3)
df['FP'] = df.apply(lambda x: AllChem.GetMorganFingerprintAsBitVect(x['ROMol'], 2, 2048), axis=1)

In [ ]:
#フィンガープリントを再計算し、リスト作成
l_2d = df['ROMol'].values.tolist()
morgan_fp = [AllChem.GetMorganFingerprintAsBitVect(x,2,2048) for x in l_2d]
#類似度を計算し、距離行列？類似度の行列？を作成
dis_matrix = [DataStructs.BulkTanimotoSimilarity(morgan_fp[i], morgan_fp[:len(l_2d)],returnDistance=True) for i in range(len(l_2d))]
dis_array = np.array(dis_matrix)
print(dis_array)

[[0.         0.82653061 0.9047619  ... 0.75824176 0.8902439  0.84042553]
 [0.82653061 0.         0.89333333 ... 0.85714286 0.90666667 0.86363636]
 [0.9047619  0.89333333 0.         ... 0.875      0.82       0.85074627]
 ...
 [0.75824176 0.85714286 0.875      ... 0.         0.85714286 0.83333333]
 [0.8902439  0.90666667 0.82       ... 0.85714286 0.         0.8125    ]
 [0.84042553 0.86363636 0.85074627 ... 0.83333333 0.8125     0.        ]]
